services:
  sftp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:80"
    environment:
      - SFTP_USER=
      - SFTP_PASSWORD=
      - SFTP_SERVER=
      - SFTP_REMOTE_DIR=/
      - SFTP_RETAIN_DAYS=7
